db:
  addr: localhost:5432
  user: root
  password: root
  name: bits
  log_queries: true

server:
  host: localhost
  port: 8080
  api_base_path: api

dir:
  assets: "/path/to/assets"
  data: "/path/to/data"
  logs: "/path/to/data"

date_format: '2006-01-02'
time_format: '15:04:05'
date_time_format: '2006-01-02 15:04:05'
