app_env: dev # dev | test | release

db:
  addr: localhost:5432
  user: root
  password: root
  name: refto
  log_queries: true

server:
  host: localhost
  port: 8080
  api_base_path: api

  # Static directive defines local and web paths.
  # Anything that is requested from "WebPath" will served from "LocalPath" as-is
  # For example if local path is set to "./web" and web path is set to "/static/"
  # requesting "/static/something.html" will serve "./web/something.html" if exists
  static:
    local_path: "./web"
    web_path: "/~/"

github:
  client_id:
  client_secret:

  data_repo: https://github.com/refto/data.git

  # This is the same secret you set on GitHub's push hook of the repo above
  data_pushed_hook_secret: SomeSecretToSignHooks

  # Data Warden is a GitHub app that helps with data checks and validation
  # https://github.com/apps/data-warden
  data_warden:
    app_id: 1 # GitHub App ID
    install_id: 1 # Installation ID
    pem_path: private-key.pem

dir:
  data: "/projects/refto/data/"
  logs: ""

auth_token_life_time: 120h