app_env: dev # dev | test | release

db:
  addr: localhost:5432
  user: root
  password: root
  name: refto
  log_queries: true

server:
  host: localhost
  port: 8080
  api_base_path: api

dir:
  data: "/projects/refto/data/"
  logs: ""
